### PR TITLE
StableDiffusion integration

### PR DESCRIPTION
**Pull request by miguelf0x**
Made interaction with Stable Diffusion WebUI running on my PC.
Tested locally, seems working.
Though, relative file locations are used, so it may break up ;)

Added command: /anime [tags]
Generates image by [tags]

### CODE REVIEW

**Comment by IHVH** [comment]
Great job! Please write your last name so that there are no mistakes.

**Comment by miguelf0x** [comment]
Tikhomirov M., 2nd group

**Comment by IHVH** [comment]
Do you have a link to the instructions for starting the stable diffusion server?

**Comment by miguelf0x** [comment]
> Do you have a link to the instructions for starting the stable diffusion server?

Yes, there are several variants of UI for SD, I personally prefer (and use) this one:
https://github.com/AUTOMATIC1111/stable-diffusion-webui

Project wiki:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki

Consider using xformers optimization, since it significantly increases performance

**Pull request merged**
